

image: python:2.7

stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - docker 
  script:
    - pip install --upgrade pip
    - pip install --upgrade awscli
    - npm install
    - npm run build
