apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  type: LoadBalancer
  externalIPs:
    - 13.236.93.74
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgresql
#### ClusterIP
# spec:
#   type: ClusterIP
#   ports:
#     - port: 5432
#   selector:
#     app: postgresql