query($userid: String!){
  users(where: {loginid: {_eq: $userid}}) {
    email
    id
    loginid
  }
  users_details(where: {users: {loginid: {_eq: $userid}}}) {
    avatarpath
    username
    userid
    blob
  }
}